import { getSession } from "@/lib/auth";
import Logo from "@/components/Logo";
import Workspace from "@/components/Workspace";
import { isGoogleAuthConfigured, getEnv } from "@/lib/env";
import { ArrowUpRight, Check, Database, FolderKey, Server, ShieldCheck } from "lucide-react";
import GuestLogin from "@/components/GuestLogin";
export const dynamic = "force-dynamic";
export default async function HomePage() {
  const session = await getSession();
  if (session) return <Workspace session={session} />;
  const registration = getEnv().PUBLIC_REGISTRATION_ENABLED;
  return <main className="auth-shell auth-v2">
    <section className="auth-story"><header className="auth-brand"><Logo size={42} /><span>salva <small>/ cloud</small></span></header><div className="auth-story-copy"><p className="eyebrow">PERSONAL CLOUD CONTROL PLANE</p><h1>Every disk.<br />One calm <em>workspace.</em></h1><p>Connect S3, WebDAV infrastructure, and your own NAS without giving up how your files are organized, accessed, or shared.</p></div><div className="auth-system-map" aria-hidden="true"><svg className="system-connectors" viewBox="0 0 630 310" preserveAspectRatio="none"><path d="M154 150 L276 78" /><path d="M354 78 L476 150" /><path d="M315 96 L315 122" /><path d="M315 182 L315 248" /></svg><div className="system-node node-primary"><span><Logo size={25} /></span><strong>Salva Cloud</strong><small>Control plane</small></div><div className="system-node node-s3"><Database size={19} /><strong>S3</strong><small>Object storage</small></div><div className="system-node node-nas"><Server size={19} /><strong>Salva Agent</strong><small>PC / server disk</small></div><div className="system-node node-gateway"><span><Logo size={21} /></span><strong>Salva Gateway</strong><small>Transfer service</small></div><div className="system-node node-dsm"><Server size={19} /><strong>DSM</strong><small>Synology storage</small></div></div><footer className="auth-trust"><span><ShieldCheck size={15} />Encrypted credentials</span><span><FolderKey size={15} />Isolated workspaces</span></footer></section>
    <section className="auth-access"><div className="access-panel"><div className="access-kicker"><span className="pulse-dot" />{registration ? "Registration open" : "Private access"}</div><h2>{registration ? "Create your cloud workspace" : "Welcome back"}</h2><p>{registration ? "Sign in with a verified Google account. A private, empty workspace will be created for you." : "Continue to your private storage workspace."}</p><div className="login-methods">{isGoogleAuthConfigured() ? <a className="google-button" href="/api/auth/google/start"><span className="google-g">G</span><span>{registration ? "Continue or register with Google" : "Continue with Google"}</span><ArrowUpRight size={17} /></a> : <p className="notice notice-error">Google sign-in is not configured.</p>}<GuestLogin /></div><div className="access-divider"><span>WHAT YOU GET</span></div><ul className="access-benefits"><li><Check size={16} /><span><strong>Separate identity</strong>Your files and connections stay scoped to your account.</span></li><li><Check size={16} /><span><strong>Provider flexibility</strong>Switch between S3, WebDAV gateways, and private NAS endpoints.</span></li><li><Check size={16} /><span><strong>Controlled sharing</strong>Expiring links, optional passwords, and revocation.</span></li></ul><p className="access-legal">By continuing, you confirm this is your account and you are authorized to connect the storage credentials you provide.</p></div></section>
  </main>;
}
