"use client";
import { useEffect, useState } from "react";
import { Loader2, X } from "lucide-react";
type PreviewFile={id:string;name:string;contentType:string;sizeBytes:number};
const extension=(name:string)=>name.split(".").pop()?.toLowerCase()??"";
export const canPreview=(file:PreviewFile)=>["png","jpg","jpeg","pdf","docx","xlsx","xls","csv"].includes(extension(file.name));
export default function FilePreview({file,storageId,onClose}:{file:PreviewFile;storageId:string;onClose:()=>void}){
 const [url,setUrl]=useState(""),[html,setHtml]=useState(""),[sheets,setSheets]=useState<Array<{name:string;rows:unknown[][]}>>([]),[error,setError]=useState("");
 useEffect(()=>{let alive=true,blobUrl="";(async()=>{try{const ext=extension(file.name);const limit=["docx","xlsx","xls","csv"].includes(ext)?25*1024**2:100*1024**2;if(file.sizeBytes>limit)throw new Error(`Preview is limited to ${limit/1024**2} MB for this format.`);const response=await fetch(`/api/files/${file.id}/download`,{headers:{"x-storage-id":storageId},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message??"Could not prepare preview");const remote=await fetch(body.url);if(!remote.ok)throw new Error("Storage did not return the file");const blob=await remote.blob();if(!alive)return;if(["png","jpg","jpeg","pdf"].includes(ext)){blobUrl=URL.createObjectURL(blob);setUrl(blobUrl);return}const data=await blob.arrayBuffer();if(ext==="docx"){const [{default:mammoth},{default:DOMPurify}]=await Promise.all([import("mammoth/mammoth.browser"),import("dompurify")]);const result=await mammoth.convertToHtml({arrayBuffer:data});if(alive)setHtml(DOMPurify.sanitize(result.value,{USE_PROFILES:{html:true}}));return}const XLSX=await import("@e965/xlsx");const workbook=XLSX.read(data,{type:"array",cellDates:true,dense:true});const parsed=workbook.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,blankrows:false,defval:""}) as unknown[][]}));if(alive)setSheets(parsed)}catch(e){if(alive)setError(e instanceof Error?e.message:"Preview failed")}})();return()=>{alive=false;if(blobUrl)URL.revokeObjectURL(blobUrl)}},[file,storageId]);
 return <div className="preview-overlay" role="dialog" aria-modal="true" aria-label={`Preview ${file.name}`}><div className="preview-shell"><header><div><small>FILE PREVIEW</small><strong>{file.name}</strong></div><button className="icon-button" onClick={onClose} aria-label="Close preview"><X size={20}/></button></header><main>{error?<div className="preview-state form-error">{error}</div>:url?(extension(file.name)==="pdf"?<iframe title={file.name} src={url}/>:<img src={url} alt={file.name}/>):html?<article className="docx-preview" dangerouslySetInnerHTML={{__html:html}}/>:sheets.length?<div className="sheet-preview">{sheets.map(sheet=><section key={sheet.name}><h3>{sheet.name}</h3><div className="sheet-scroll"><table><tbody>{sheet.rows.slice(0,5000).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{String(cell??"")}</td>)}</tr>)}</tbody></table></div></section>)}</div>:<div className="preview-state"><Loader2 className="spinning"/>Preparing preview…</div>}</main></div></div>;
}
