"use client";
import { useEffect, useState } from "react";
import { Copy, Eye, EyeOff, File, Folder, Link2, RefreshCw, Search, Trash2 } from "lucide-react";
import Select from "./Select";
type ShareLink = { id: string; kind: "file" | "folder"; name: string; storageName?: string; expiresAt: string; revokedAt: string | null; unavailable: boolean; passwordProtected: boolean; url: string | null; password?: string | null };
export default function ShareLinksManager() {
  const [links, setLinks] = useState<ShareLink[]>([]), [canRevealPassword, setCanRevealPassword] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [filter, setFilter] = useState("all"), [revealed, setRevealed] = useState<string[]>([]), [busy, setBusy] = useState(""), [notice, setNotice] = useState(""), [now, setNow] = useState(0);
  const status = (link: ShareLink) => link.revokedAt ? "revoked" : new Date(link.expiresAt).getTime() <= now ? "expired" : link.unavailable ? "unavailable" : "active";
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/share-links", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message); setLinks(body.links); setCanRevealPassword(body.canRevealPassword); setNow(Date.now()); } catch (error) { setError(error instanceof Error ? error.message : "Could not load share links"); } finally { setLoading(false); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 0); const tick = setInterval(() => setNow(Date.now()), 30_000); return () => { clearTimeout(timer); clearInterval(tick); }; }, []);
  async function revoke(link: ShareLink) { if (busy) return; setBusy(link.id); setError(""); try { const response = await fetch(`/api/share-links/${link.id}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) throw new Error(body.message); setNotice(`Link for ${link.name} revoked.`); await load(); } catch (error) { setError(error instanceof Error ? error.message : "Could not revoke link"); } finally { setBusy(""); } }
  async function copy(value: string, label: string) { try { await navigator.clipboard.writeText(value); setNotice(`${label} copied.`); } catch { setError("Clipboard is unavailable. Select the value and copy it manually."); } }
  const visible = links.filter(link => (filter === "all" || status(link) === filter) && `${link.name} ${link.storageName ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="links-manager"><div className="toolbar"><label className="search-box"><Search size={18} /><input placeholder="Search files, folders, or storage…" aria-label="Search share links" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="toolbar-actions"><Select label="Filter share status" value={filter} onChange={setFilter} options={[{ value: "all", label: "All links" }, { value: "active", label: "Active" }, { value: "expired", label: "Expired" }, { value: "revoked", label: "Revoked" }, { value: "unavailable", label: "Unavailable" }]} /><button className="icon-button" aria-label="Refresh share links" disabled={loading} onClick={() => void load()}><RefreshCw size={18} /></button></div></div>{error && <p className="notice notice-error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}<p className="helper links-policy">All shared files and folders across your storage connections. Revocation blocks new requests; issued download URLs may last up to 5 minutes.</p>
    {loading ? <div className="loading-state">Loading share links…</div> : !visible.length ? <div className="empty-state"><Link2 size={28} /><h3>{query || filter !== "all" ? "No matching links" : "No shared links yet"}</h3><p>Create a link from a file or folder in your workspace.</p></div> : <div className="managed-links">{visible.map(link => <article className="managed-link" key={link.id}><header><span className="file-icon">{link.kind === "folder" ? <Folder size={21} /> : <File size={21} />}</span><div><h2>{link.name}</h2><p>{link.kind === "folder" ? "Folder · includes subfolders" : "File"} · {link.storageName ?? "Disconnected storage"}</p></div><span className={`link-status ${status(link)}`}>{status(link)}</span></header><div className="managed-link-details"><div><span className="field-caption">Share link</span>{link.url ? <div className="secret-value"><input aria-label={`Link for ${link.name}`} value={link.url} readOnly onFocus={event => event.target.select()} /><button className="icon-button" aria-label={`Copy link for ${link.name}`} onClick={() => void copy(link.url!, "Link")}><Copy size={16} /></button></div> : <p className="helper">This older link cannot be recovered. Create a new link.</p>}</div>{canRevealPassword && <div><span className="field-caption">Password</span>{link.password ? <div className="secret-value"><input aria-label={`Password for ${link.name}`} type={revealed.includes(link.id) ? "text" : "password"} value={link.password} readOnly onFocus={event => event.target.select()} /><button className="icon-button" aria-label={`${revealed.includes(link.id) ? "Hide" : "Reveal"} password for ${link.name}`} onClick={() => setRevealed(current => current.includes(link.id) ? current.filter(id => id !== link.id) : [...current, link.id])}>{revealed.includes(link.id) ? <EyeOff size={16} /> : <Eye size={16} />}</button><button className="icon-button" aria-label={`Copy password for ${link.name}`} onClick={() => void copy(link.password!, "Password")}><Copy size={16} /></button></div> : <p className="helper">{link.passwordProtected ? "Older password cannot be recovered." : "No password"}</p>}</div>}</div><footer><span>Expires {new Date(link.expiresAt).toLocaleString("en", { dateStyle: "medium", timeStyle: "short" })}{!canRevealPassword && link.passwordProtected ? " · Password protected" : ""}</span>{!link.revokedAt && <button className="button button-quiet danger-text" disabled={Boolean(busy)} onClick={() => void revoke(link)}><Trash2 size={15} />{busy === link.id ? "Revoking…" : "Revoke link"}</button>}</footer></article>)}</div>}
  </section>;
}
